import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

const marks = Array(12).fill(0);

const Home: NextPage = () => {
  let [time, setTime] = useState({
    second: 0,
    hour: 0,
    minute: 0,
  });

  useEffect(() => {
    const secondInterval = setInterval(() => {
      const update: any = { second: (time.second + 6) % 360 };

      if (time.second === 359) {
        update.minute = (time.minute + 6) % 360;
      }

      setTime(() => ({ ...time, ...update }));
    }, 1000);

    return () => clearTimeout(secondInterval);
  }, [time, time.second]);

  useEffect(() => {
    const now = new Date();

    const hourDegrees = 30 * (now.getHours() % 12) + now.getMinutes() / 2;
    const minutesDegrees = 6 * now.getMinutes();

    setTime({
      hour: hourDegrees,
      minute: minutesDegrees,
      second: 6 * now.getSeconds(),
    });
  }, []);

  return (
    <div className="h-screen">
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-full flex justify-center bg-gray-300">
        <div className="h-full bg-white w-[100vh] rounded-full border-slate-700 border-4 flex justify-center items-center relative">
          <div className="top-[calc(95vh/10)] absolute">
            {Math.floor(time.hour / 30)}:{Math.floor(time.minute / 6)}:
            {time.second / 6}
          </div>
          <div
            style={{ transform: `rotate(${time.second}deg)` }}
            className={`rounded-b-full h-[calc(95vh/2)] bottom-[calc(100vh/2)] origin-bottom w-1 bg-red-700 absolute`}
          ></div>
          <div
            style={{ transform: `rotate(${time.minute}deg)` }}
            className={`rounded-b-full h-[calc(90vh/2)] bottom-[calc(100vh/2)] origin-bottom w-2 bg-slate-700 absolute`}
          ></div>
          <div
            style={{ transform: `rotate(${time.hour}deg)` }}
            className={`rounded-b-full h-[calc(50vh/2)] bottom-[calc(100vh/2)] origin-bottom w-4 bg-slate-700 absolute`}
          ></div>
          {marks.map((key, index) => (
            <div
              style={{
                transform: `rotate(${index * 30}deg)`,
              }}
              key={index}
              className="h-20 w-4 bg-slate-700 absolute origin-center"
            ></div>
          ))}
        </div>
      </main>
    </div>
  );
};

export default Home;
